CLASS zcl_amdp_6_fuzzy_search DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.
    CLASS-METHODS get_data
        FOR TABLE FUNCTION zcds_amdp_6_FUZZY_SEARCH.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_amdp_6_fuzzy_search IMPLEMENTATION.
  METHOD get_data
* AMDP Table Function
BY DATABASE FUNCTION FOR HDB LANGUAGE SQLSCRIPT "OPTIONS READ-ONLY
USING ZSCARRX.

RETURN

 SELECT MANDT, SCORE( ) AS SCORE, CARRID, CARRNAME
             FROM ZSCARRX
*             WHERE CONTAINS ( CARRNAME, CARR_NAME, FUZZY( 0.5 )) AND MANDT = '100' ORDER BY 1;
             WHERE CONTAINS ( CARRNAME, CARR_NAME, FUZZY( 0.1 )) AND MANDT = '100' ORDER BY 1;

ENDMETHOD.
ENDCLASS.
